# Generated by Django 3.2.8 on 2021-10-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_information', '0005_auto_20211014_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
