# Generated by Django 3.2.8 on 2021-10-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_information', '0007_rename_username_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
