# Generated by Django 3.2.8 on 2021-10-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_information', '0008_rename_user_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
