# Generated by Django 3.2.8 on 2021-10-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_information', '0010_extenduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendUser',
        ),
    ]
