# Generated by Django 3.2.8 on 2021-10-14 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_information', '0001_initial'),
        ('user_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('status', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usercarts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.SmallIntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product_information.succulents')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usercarts.statuses')),
                ('user_uuid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_information.profile')),
            ],
        ),
    ]
