# Generated by Django 3.2.8 on 2021-10-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='usercart',
            old_name='user_id',
            new_name='user',
        ),
    ]
