# Generated by Django 3.2.8 on 2021-10-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercart', '0002_auto_20211020_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='status',
            field=models.CharField(default='Close', max_length=10),
        ),
        migrations.DeleteModel(
            name='Statuses',
        ),
    ]
